PREFIX dimlex: <https://github.com/discourse-lab/dimlex/blob/master/DimLex.dtd#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX pdtb: <http://purl.org/olia/discourse/discourse.PDTB.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#LOAD <http://purl.org/olia/discourse/discourse.PDTB.owl>; 
LOAD <file:///C:/Users/chiarcos/Desktop/olia/trunk/owl/experimental/discourse/discourse.PDTB.owl>;

INSERT {
        ?dimlex_relation ontolex:reference ?pdtb_sense.
} WHERE {
        ?dimlex_relation dimlex:sense ?label.
        ?pdtb_sense (rdfs:label|skos:altLabel) ?sense_label.
        FILTER(lcase(?label)=lcase(?sense_label))
};

MOVE DEFAULT TO <http://placehold.er>;

INSERT {
	?a ?b ?c
} WHERE {
	GRAPH <http://placehold.er> {
		?a ?b ?c
		FILTER(strstarts(str(?b),'http://www.w3.org/ns/lemon/ontolex#') || strstarts(str(?c),'http://www.w3.org/ns/lemon/ontolex#'))
	}
};

DROP GRAPH <http://placehold.er>