# if URIs appear in a string annotation of a nif:Word, replace them by their local names 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xml: <http://www.w3.org/TR/xml/#>
prefix conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>

DELETE {
	?word ?prop ?original.
} INSERT {
	?word ?prop ?simple.
} WHERE {
	?word a nif:Word.
	?word ?prop ?original.
	FILTER(regex(?original,'[a-z]+:\\/[^ \t\n]*[\\/#]'))
	BIND(replace(?original,'[a-z]+:\\/[^ \t\n]*[\\/#]','') AS ?simple)
};